### PR TITLE
Included screenshots to allow the Richer PWA installation UI on Chrome

### PR DESCRIPTION
**Pull request by JessFairbairn**
Simple question of including screenshots, let me know what you think of the screenshots and the directory name (/img/screenshots) etc.

### CODE REVIEW

**Comment by JessFairbairn** [comment]
#86

**Review by CanopusFalling — APPROVED** [review]
Sitemap CI looks to be broken, will push through and override that, we need to redo the end to end CI anyways.
Thank you for catching my use of console.log instead of console.error in `getEvents.tsx` good reminder I need to overhaul the error handling in this project at some point.
All looks good chrome thinks it passes the bar for richer install in testing. Thanky for submitting!

**Comment by CanopusFalling** [comment]
close #86

**Comment by CanopusFalling** [comment]
@JessFairbairn Just wanna check, I'm about to add an MIT liscence to the project, are you happy releasing your work under the MIT licence? I'll merge this in once you let me know that's good.

**Comment by JessFairbairn** [comment]
That's fine by me!

**Pull request merged**
